### ISSUE TITLE
Issue in viewing the experiment in MLflow 

### ISSUE THREAD

**Issue by mukul74** [GokuMohandas/Made-With-ML#210]
I am running the tagifai.ipynb notebook on the **windows** platform but facing difficulty viewing the experiment in MLflow.

**Steps Done**:
1. Cloned the repo
2. Running the  "`mlops-course\notebooks\tagifai.ipynb`" in vs code locally.
3. To run the server "`mlflow server -h 0.0.0.0 -p 8000 --backend-store-uri /experiments/`" from the location of the notebook, experiments is the next folder inside it. # $PWD is omitted because of windows.
4. Opening the "http://localhost:8000/#/"

**Observation** : 
1. No signs of experiment run.
2. Image attached below for ref.
![image](https://user-images.githubusercontent.com/5962451/186658579-6cf3c711-dff2-465e-a3e4-1c5d71282458.png)

Please provide assistance with this issue.

Thanks

**Comment by GokuMohandas** [comment]
Hi @mukul74, hmm I've heard from few others who had trouble running MLFLow on Windows as well. Have you tried the "Tip" on this page: https://madewithml.com/courses/mlops/experiment-tracking/#application

On Windows, the last line where we set the tracking URI should have three forwards slashes:
```python
mlflow.set_tracking_uri("file:///" + str(MODEL_REGISTRY.absolute()))
```

Let me know if that works! I'll add this tip to the notebook as well but definitely check out the website lessons as your go through the code because I try not to add too much text on the notebooks to avoid clutter.
