### ISSUE TITLE
Missing some topics after updates

### ISSUE THREAD

**Issue by Lavreniuk** [GokuMohandas/Made-With-ML#233]
I sincerely appreciate your work and find the materials you provide to be incredibly useful. However, I've noticed that some valuable topics have disappeared after the last updates. I kindly request you to reinstate those topics, such as CLI (though it currently exists, it lacks substantial material), Optuna optimization, Airflow, Git, Feature store, and others.
For example here is old link and it provides error 404:
[https://madewithml.com/courses/mlops/optimization/](https://madewithml.com/courses/mlops/optimization/
)

**Comment by GokuMohandas** [comment]
Hey @Lavreniuk , a lot of content is outdated, weaved into existing lessons (like Git), not created for ML at scale and frankly overengineering. But here are the links if you really want to see this:

optimization: ttps://madewithml.com/courses/mlops/tuning/
airflow: https://madewithml.com/courses/mlops/orchestration/
git: https://madewithml.com/courses/mlops/git/
feature store: https://madewithml.com/courses/mlops/feature-store/

**Comment by innat** [comment]
@GokuMohandas Hello. 
Is it possible to place this content (especially git) on the landing page (in some way)? Also, I think the git lesson is important, especially for [CI/CD lessons](https://madewithml.com/courses/mlops/cicd/).

**Comment by GokuMohandas** [comment]
These lessons are still there but interweaved throughout the lessons. For example, in the [versioning lesson](https://madewithml.com/courses/mlops/versioning/#code), you can find the "Tip" that has a link to the Git lesson. We won't need Git until this point in the course. I mostly removed it because there are many way better places to learn about git and I didn't want to crowd this advanced content with too many beginner topics. Here is the git lesson if you still need it: https://madewithml.com/courses/mlops/git/

**Comment by GokuMohandas** [comment]
@innat These lessons are still there but interweaved throughout the lessons. For example, in the [versioning lesson](https://madewithml.com/courses/mlops/versioning/#code), you can find the "Tip" that has a link to the Git lesson. We won't need Git until this point in the course. I mostly removed it because there are many way better places to learn about git and I didn't want to crowd this advanced content with too many beginner topics. Here is the git lesson if you still need it: https://madewithml.com/courses/mlops/git/
